default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["PGUSER"] || ENV["USER"] %>
  password: <%= ENV["PGPASSWORD"] || "" %>
  host: <%= ENV["PGHOST"] || "localhost" %>

development:
  <<: *default
  database: my_dinner_development

test:
  <<: *default
  database: my_dinner_test

production:
  primary:
    <<: *default
    database: my_dinner_production
  cache:
    <<: *default
    database: my_dinner_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: my_dinner_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: my_dinner_production_cable
    migrations_paths: db/cable_migrate
